/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author omar
 */
public class VentanaAlgoritmoDispersion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAlgoritmoDispersion
     */
    public VentanaAlgoritmoDispersion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoLlave = new javax.swing.JTextField();
        BotonDivision = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTextoResultado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextoTamano = new javax.swing.JTextField();
        BotonMidsquare = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TextoNumeroBitsCentrales = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextoNumeroBitsGrupo = new javax.swing.JTextField();
        BotonPlegamiento = new javax.swing.JButton();
        TextoBase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BotonTransformacionLlaves = new javax.swing.JButton();
        TextoTamanoArreglo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonDivision.setText("División");
        BotonDivision.setName(""); // NOI18N
        BotonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDivisionActionPerformed(evt);
            }
        });

        AreaTextoResultado.setColumns(20);
        AreaTextoResultado.setRows(5);
        jScrollPane1.setViewportView(AreaTextoResultado);

        jLabel1.setText("Digite Llave:");

        jLabel2.setText("Digite Tamaño del Arreglo:");

        BotonMidsquare.setText("Midsquare");
        BotonMidsquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMidsquareActionPerformed(evt);
            }
        });

        jLabel3.setText("Digite Número de Bits Centrales:");

        jLabel4.setText("Digite Número de bits de cada grupo:");

        BotonPlegamiento.setText("Plegamiento");
        BotonPlegamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPlegamientoActionPerformed(evt);
            }
        });

        jLabel5.setText("Digite la Base:");

        jLabel6.setText("Digite Tamaño del Arreglo:");

        BotonTransformacionLlaves.setText("Transformación Llaves");
        BotonTransformacionLlaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTransformacionLlavesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(TextoLlave, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoBase)
                            .addComponent(TextoTamanoArreglo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(TextoNumeroBitsGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonDivision, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonMidsquare, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonPlegamiento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonTransformacionLlaves, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoNumeroBitsCentrales)
                            .addComponent(TextoTamano))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoLlave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextoTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonDivision)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextoNumeroBitsCentrales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonMidsquare)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextoNumeroBitsGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonPlegamiento)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoTamanoArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonTransformacionLlaves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDivisionActionPerformed
        AreaTextoResultado.setText("");
        Dispersion Dispersion1 = new Dispersion(Integer.parseInt(TextoLlave.getText()));
        AreaTextoResultado.setText("Número Dispersión División: " + Integer.toString(Dispersion1.division(Integer.parseInt(TextoTamano.getText()))));
    }//GEN-LAST:event_BotonDivisionActionPerformed

    private void BotonMidsquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMidsquareActionPerformed
        AreaTextoResultado.setText("");
        Dispersion Dispersion1 = new Dispersion(Integer.parseInt(TextoLlave.getText()));
        AreaTextoResultado.setText("Número Dispersión Midsquare: " + Integer.toString(Dispersion1.midsquare(Integer.parseInt(TextoNumeroBitsCentrales.getText()))));
    }//GEN-LAST:event_BotonMidsquareActionPerformed

    private void BotonPlegamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPlegamientoActionPerformed
        AreaTextoResultado.setText("");
        Dispersion Dispersion1 = new Dispersion(Integer.parseInt(TextoLlave.getText()));
        AreaTextoResultado.setText("Número Dispersión Plegamiento: " + Integer.toString(Dispersion1.plegamiento(Integer.parseInt(TextoNumeroBitsGrupo.getText()))));
    }//GEN-LAST:event_BotonPlegamientoActionPerformed

    private void BotonTransformacionLlavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTransformacionLlavesActionPerformed
        AreaTextoResultado.setText("");
        Dispersion Dispersion1 = new Dispersion(Integer.parseInt(TextoLlave.getText()));
        AreaTextoResultado.setText("Número Dispersión Transformación Llaves: " + Integer.toString(Dispersion1.transformacionLlaves(Integer.parseInt(TextoBase.getText()), Integer.parseInt(TextoTamanoArreglo.getText()))));
    }//GEN-LAST:event_BotonTransformacionLlavesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAlgoritmoDispersion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAlgoritmoDispersion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAlgoritmoDispersion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAlgoritmoDispersion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAlgoritmoDispersion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTextoResultado;
    private javax.swing.JButton BotonDivision;
    private javax.swing.JButton BotonMidsquare;
    private javax.swing.JButton BotonPlegamiento;
    private javax.swing.JButton BotonTransformacionLlaves;
    private javax.swing.JTextField TextoBase;
    private javax.swing.JTextField TextoLlave;
    private javax.swing.JTextField TextoNumeroBitsCentrales;
    private javax.swing.JTextField TextoNumeroBitsGrupo;
    private javax.swing.JTextField TextoTamano;
    private javax.swing.JTextField TextoTamanoArreglo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
